Repository schubergphilis/terraform-aws-mcaf-energy-labeler, pull requests merged in 2024-09, with the labels that each got.

#3 feat: First version
  .gitignore
  .terraform.lock.hcl
  CHANGELOG.md
  README.md
  examples/basic/kms.tf
  examples/basic/main.tf
  examples/basic/versions.tf
  main.tf
  output.tf
  variables.tf
  versions.tf
Labels: feature

#2 feat: initial refactor
  .gitignore
  .terraform.lock.hcl
  README.md
  examples/basic/kms.tf
  examples/basic/main.tf
  main.tf
  output.tf
  outputs.tf
  terraform.tf
  variables.tf
  versions.tf
Labels: feature

#5 misc: Remove unused configuration options
  README.md
  examples/basic/main.tf
  main.tf
  variables.tf
Labels: misc

#4 misc: Add encryption
  README.md
  examples/basic/main.tf
  main.tf
  variables.tf
Labels: feature, misc
